language: node_js

node_js:
  - "7"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - develop

script:
  - ls -la

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/d-kusk/minimage.git
  - secure: "AkE+gHoppmu8gGQYI7LIchrpFV0HYKqxLxNkUThnVqKDLrjDEcE8QLLWtM2Ug+jjSCKeDCg4IHH8YTDSno042c/j4jcI0pFexVLDnOnJ5S+36wJ+2DpPBNoEIleb9wLvOHuBhnnyy69BjVb3uQim6/OC85zWV4FAxRTbl6/9sk8vZ3kCg+lLaHbuFT9bqnFHIhb0Qh11UevMl4C0jsUh/PHAM8TURFoXnYSagLv3uqMBgTl4fupmqTS+LreigWbYxExwwaonwm3Hsl3B2wr7N+5KkRLippOtzj21lHgRt4YJzrTUq8qwSMEjKLu/DysRXKKStuouaOg7QOooxrUsV+Nrp95mrxI8tSxZYOLNTAOogRMLlC7Md9hyuDEHPtdef/0wT4tkrijyNLN0j005Mpn2Rjz2yRNhORbsLIUiUxVo6zk75KKPfSMRK9u6IhXhAnduRxzxIGpGshmWbuaXavUY+kTt+5rCCRPpkASmKJ9ww4tfO2BqYcz8/ZsnbGTY1ycyg8aRvxmoMj0IK2ciMh1HB+SbPf8YuttwI35niCIfE1ta+eitFEts8FqtaKVGxAdejC++qnSnaSvat06I+cSgOSodOK6ATuN+EnT8+MubO79mmfxJdptK+siqIIHFL/Bnj0aqM+AvE3R93bpNcMRjr3J/6AlD9IKql5A7c1M="
